[build-system]
requires = ["setuptools>=61.0","numpy>=2", "setuptools_scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wfss-tools"
dynamic = ["version"]
authors = [
  { name="Peter J. Watson", email="peter.watson+NT@inaf.it" },
]
description = "A set of tools for processing JWST NIRISS/WFSS data."
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    "astropy>=6.1",
    "numpy>=2.0.0",
    "matplotlib>=3.9",
    "tqdm>=4.67",
    "scipy>=1.18",
    "reproject>=0.14",
    "drizzlepac>=3.11.0",
    "photutils>=3.0",
    "shapely>=2.0.4",
    "grizli[jwst,aws]@git+https://github.com/PJ-Watson/grizli@new_workflow",
    "pypher>=0.7.3",
    "tomlkit",
    "psutil"
]

[project.optional-dependencies]
adaptive-binning = [
    "vorbin",
    "powerbin",
]
bagpipes = [
    "bagpipes-extended@git+https://github.com/PJ-Watson/bagpipes-extended",
    "bagpipes>=1.3.6",
]
all = ["wfss-tools[adaptive-binning, bagpipes]"]

[project.urls]
"Homepage" = "https://github.com/PJ-Watson/wfss-tools"
"Bug Tracker" = "https://github.com/PJ-Watson/wfss-tools/issues"

[tool.setuptools.package-data]
"*" = ["*.*"]

[tool.black]
line-length = 88
target-version = ["py313"]
extend-exclude = "(.*.txt|.*.md|.*.toml|.*.odg)"
preview = true

[tool.isort]
profile = "black"

[tool.numpydoc_validation]
checks = [
    "all",   # report on all checks, except the below
    "EX01",
    "SA01",
    "ES01",
    "RT01",
]
exclude = [  # don't report on objects that match any of these regex
    '\.undocumented_method$',
    '\.__repr__$',
    '\._.*$',  # Ignore anything that's private (e.g., starts with _)
]
override_SS05 = [  # override SS05 to allow docstrings starting with these words
    '^Process ',
    '^Assess ',
    '^Access ',
]

[tool.setuptools_scm]
version_file = "src/wfss_tools/_version.py"


[dependency-groups]
dev = [
    "pre-commit>=4.5"
]
docs = [
    "sphinx-copybutton>=0.5",
    "sphinx<9.0",
    "numpydoc>=1.10",
    "sphinx-astropy>=1.10",
    "pydata-sphinx-theme>=0.16.1"
]
